public enum UiPanelType
{
    None,
    MainScreen,
    MapScreen,
    PopupSetting,
    PopupRate,
    PopupTutorial,
    PopupNoInternet,
    PopupNotification,
    PlayScreen,
    DemoPopup,
    DemoBottomPopup,
    DemoSidePopup,
    ScreenDemoShop,
    PopupOnlineReward,
    PopupLuckyWheel,
    PopupOfflineReward,
    PopupChestRoom,
    PopupDailyReward,
    PopupLeaderboard,
    PopupPauseGame,
    PopupSelectMap,
    SdkPlaceHolder //Do not rename or re-arrange
}